### ISSUE TITLE
Plugin Authorization process not using WP_PROXY_* definitions

### ISSUE THREAD

**Issue by kuiperr005** [deconf/Google-Analytics-Dashboard-for-WP#128]
The Authorization process of the plugin does not seem to use the Wordpress proxy settings if those are defined in the wp_config:

If have defined the following proxy settings in `wp-config.php`:
`define('WP_PROXY_HOST', 'my.proxy.host');` and `define('WP_PROXY_PORT', 'XXXX');` (HOST and PORT is using sample data for this issue)

**Steps to reproduce:**
- Install the GADfWP plugin
- Make sure WP_PROXY_HOST and WP_PROXY_PORT are set to valid fields in `wp-config.php`
- Go to the base settings of the plugin and click on 'Authorize plugin'
- Connect to your Google Analytics account and copy the code
- Fill in the code into the 'Access code' input field and click on 'Save access code'
- Go to Error & Debug and view the Error log. You should see a message like: `exception 'Google_IO_Exception' with message 'Failed to connect to gadwp.deconf.com port 443: Connection refused' in /srv/www/clients/client208/web247/web/app/plugins/google-analytics-dashboard-for-wp/tools/src/Deconf/IO/Curl.php:126`

**Comment by deconf** [comment]
Done! If you could test it would be great.

Thank you for the report!

**Comment by kuiperr005** [comment]
Thanks, Just tested it. 

The authorization seems to come through, but I still get an error and I don't see any properties in the list. This is the error I get after authorization: 
`exception 'Google_IO_Exception' with message 'Received HTTP code 403 from proxy after CONNECT' in /web/app/plugins/Google-Analytics-Dashboard-for-WP-master/tools/src/Deconf/IO/Curl.php:126`

**Comment by deconf** [comment]
Awesome, thanks for the feedback!
